# Intro to NumPy, SciPy, and Matplotlib

## NumPy

In [7]:
import numpy as np

### Comparison of NumPy Array and List

In [2]:
x = [2, 3, 4, 6] #usual Python list
y = np.array(x) #numpy array

In [3]:
print(type(x), x)
print(type(y), y)

<class 'list'> [2, 3, 4, 6]
<class 'numpy.ndarray'> [2 3 4 6]


In [4]:
print(x[1:3])

[3, 4]


In [5]:
print(y[1:3])

[3 4]


In [6]:
print(x[[0, 2]])

TypeError: list indices must be integers or slices, not list

In [7]:
print(y[[0, 2]])

[2 4]


In [8]:
print(y[y>3])

[4 6]


In [9]:
print(x * 5)

[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]


In [10]:
print(y * 5)

[10 15 20 30]


In [11]:
print(x ** 2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [12]:
print(y ** 2)

[ 4  9 16 36]


In [13]:
matrix = [[1, 2, 4], [3, 1, 0]]
nd_array = np.array(matrix)

In [14]:
print(matrix[1][2])

0


In [15]:
print(nd_array[1, 2])

0


In [16]:
print(np.random.rand())

0.13735299485294405


In [17]:
print(np.random.randn())

0.4211408818442855


In [18]:
print(np.random.randn(4))

[ 0.28990917  0.45756145  0.0723704  -0.49627543]


In [19]:
print(np.random.randn(4, 5))

[[-1.5857039   0.00890419 -1.03182142 -0.19166176 -0.16541785]
 [-2.01018593 -1.51627111 -1.22841524  0.7572365   1.57797944]
 [ 1.65637736 -0.38514528 -0.6716131  -0.64267973 -1.86547762]
 [ 1.11174737  1.80757118  0.31828113 -0.05810543  2.17092619]]


### range() Method in Python and arange() in NumPy

In [20]:
print(np.arange(0, 8, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]


In [22]:
list(range(0, 8, 1))

[0, 1, 2, 3, 4, 5, 6, 7]

In [23]:
%timeit np.arange(0, 10000)
%timeit range(0, 10000)

5.06 µs ± 103 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
148 ns ± 1.98 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


## SciPy

In [1]:
from scipy import optimize

In [2]:
def f(x):
    return (x[0] - 3.2) ** 2 + (x[1] - 0.1) ** 2 + 3

print(f([3.2, 0.1]))

3.0


In [3]:
x_min = optimize.minimize(f, [5, 5])
print(x_min)

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 3.0000000000012976
        x: [ 3.200e+00  1.000e-01]
      nit: 3
      jac: [-2.146e-06  7.749e-07]
 hess_inv: [[ 9.406e-01 -1.618e-01]
            [-1.618e-01  5.594e-01]]
     nfev: 12
     njev: 4


In [4]:
print(x_min.x)

[3.19999893 0.10000038]


In [5]:
from scipy import linalg

In [9]:
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])

x = linalg.solve(a, b)
print(x)

[ 2. -2.  9.]


In [10]:
print(np.dot(a, x))

[ 2.  4. -1.]


In [11]:
X = np.random.randn(4, 3)
U, D, V = linalg.svd(X)
print(U.shape, D.shape, V.shape)
print(type(U), type(D), type(V))

(4, 4) (3,) (3, 3)
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
